# Generated by Django 5.2.17 on 2026-08-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking_request',
            index=models.Index(fields=['lsa', 'status', 'start_time', 'end_time'], name='booking_api_lsa_id_188a88_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking_request',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='check_start_time_before_end_time'),
        ),
    ]
